input {
  file {
    path => "/var/log/app/backend/*.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
    tags => ["backend"]
  }

  http {
    port => 5000
    codec => json
    tags => ["frontend"]
  }
}

filter {
  mutate {
    add_field => { "environment" => "development" }
    add_field => { "type" => "%{[tags][0]}" }
    remove_field => [ "@version" ]
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "logs-%{[type]}-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
